# Generated by Django 3.2.7 on 2021-10-20 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='honorific',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MS', 'Ms.'), ('DR', 'Dr.'), ('', '')], default='', max_length=2),
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.employee')),
                ('guestid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.guest')),
                ('roomid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.room')),
            ],
        ),
    ]
